config/routes.rb
Rails.application.routes.draw do
  resources :insta_posts
  resources :insta_tags
  resources :insta_accounts
  resources :moniitors
  resources :articles
  resources :stories
  resources :posts
  resources :events
  resources :topics
  get 'welcome/index'
  get 'welcome/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :story
  mount_uploader :image, ImageUploader
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :topic
  has_many :posts
  mount_uploader :image, ImageUploader
  validates :topic_id, presence: true
end

app/models/insta_account.rb
class InstaAccount < ApplicationRecord
end

app/models/insta_post.rb
class InstaPost < ApplicationRecord
end

app/models/insta_tag.rb
class InstaTag < ApplicationRecord
end

app/models/moniitor.rb
class Moniitor < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :event
  has_many :stories
  accepts_nested_attributes_for :stories

  def stories_for_form
    collection = stories.where(post_id: id)
    collection.any? ? collection : stories.build
  end

  def next
    Story.where("id > ?", id).order(id: :asc).limit(1).first
  end

  def prev
    Story.where("id < ?", id).order(id: :desc).limit(1).first
  end
  
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :post
  has_many :articles
  mount_uploader :image, ImageUploader
  # accepts_nested_attributes_for :post

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :events
  has_many :posts
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @topics = Topic.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @posts = @event.posts
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :teaser, :topic_id, :date, :time, :place, :link, :image)
    end
end

app/controllers/insta_posts_controller.rb
class InstaPostsController < ApplicationController
  before_action :set_insta_post, only: [:show, :edit, :update, :destroy]

  # GET /insta_posts
  # GET /insta_posts.json
  def index
    @insta_posts = InstaPost.all
  end

  # GET /insta_posts/1
  # GET /insta_posts/1.json
  def show
  end

  # GET /insta_posts/new
  def new
    @insta_post = InstaPost.new
  end

  # GET /insta_posts/1/edit
  def edit
  end

  # POST /insta_posts
  # POST /insta_posts.json
  def create
    @insta_post = InstaPost.new(insta_post_params)

    respond_to do |format|
      if @insta_post.save
        format.html { redirect_to @insta_post, notice: 'Insta post was successfully created.' }
        format.json { render :show, status: :created, location: @insta_post }
      else
        format.html { render :new }
        format.json { render json: @insta_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insta_posts/1
  # PATCH/PUT /insta_posts/1.json
  def update
    respond_to do |format|
      if @insta_post.update(insta_post_params)
        format.html { redirect_to @insta_post, notice: 'Insta post was successfully updated.' }
        format.json { render :show, status: :ok, location: @insta_post }
      else
        format.html { render :edit }
        format.json { render json: @insta_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insta_posts/1
  # DELETE /insta_posts/1.json
  def destroy
    @insta_post.destroy
    respond_to do |format|
      format.html { redirect_to insta_posts_url, notice: 'Insta post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insta_post
      @insta_post = InstaPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insta_post_params
      params.require(:insta_post).permit(:moniitor_id, :insta_account_id, :insta_tag_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @topics = Topic.all
    @posts = Post.all
  end

  # GET /posts/1s
  # GET /posts/1.json
  def show
    @stories = @post.stories
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:event_id, :topic_id, stories_attributes: [:teaser, :teaser_two, :image, :post_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/insta_posts_helper.rb
module InstaPostsHelper
end

app/helpers/insta_tags_helper.rb
module InstaTagsHelper
end

app/helpers/moniitors_helper.rb
module MoniitorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/insta_posts/_form.html.erb
<body class="insta_body">

  <%= form_with(model: insta_post, local: true) do |form| %>
    <% if insta_post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(insta_post.errors.count, "error") %> prohibited this insta_post from being saved:</h2>

        <ul>
          <% insta_post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :moniitor_id %>
      <%= form.number_field :moniitor_id %>
    </div>

    <div class="field">
      <%= form.label :insta_account_id %>
      <%= form.number_field :insta_account_id %>
    </div>

    <div class="field">
      <%= form.label :insta_tag_id %>
      <%= form.number_field :insta_tag_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</body>

app/views/insta_posts/edit.html.erb
<h1>Editing Insta Post</h1>

<%= render 'form', insta_post: @insta_post %>

<%= link_to 'Show', @insta_post %> |
<%= link_to 'Back', insta_posts_path %>

app/views/insta_posts/index.html.erb
<body class="insta_body">

  <h1>Insta Posts</h1>

  <table>
    <thead>
      <tr>
        <th>Moniitor</th>
        <th>Insta account</th>
        <th>Insta tag</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @insta_posts.each do |insta_post| %>
        <tr>
          <td><%= insta_post.moniitor_id %></td>
          <td><%= insta_post.insta_account_id %></td>
          <td><%= insta_post.insta_tag_id %></td>
          <td><%= link_to 'Show', insta_post %></td>
          <td><%= link_to 'Edit', edit_insta_post_path(insta_post) %></td>
          <td><%= link_to 'Destroy', insta_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Insta Post', new_insta_post_path %>

</body>

app/views/insta_posts/new.html.erb
<body class="insta_body">

  <h1>New Insta Post</h1>

  <%= render 'form', insta_post: @insta_post %>

  <%= link_to 'Back', insta_posts_path %>


</body>

app/views/insta_posts/show.html.erb
<body class="insta_body">

  <p>
    <strong>Moniitor:</strong>
    <%= @insta_post.moniitor_id %>
  </p>

  <p>
    <strong>Insta account:</strong>
    <%= @insta_post.insta_account_id %>
  </p>

  <p>
    <strong>Insta tag:</strong>
    <%= @insta_post.insta_tag_id %>
  </p>

  <%= link_to 'Edit', edit_insta_post_path(@insta_post) %> |
  <%= link_to 'Back', insta_posts_path %>


</body>