config/routes.rb
Rails.application.routes.draw do
  resources :insta_posts
  resources :insta_tags
  resources :insta_accounts
  resources :moniitors
  resources :articles
  resources :stories
  resources :posts
  resources :events
  resources :topics
  get 'welcome/index'
  get 'welcome/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :story
  mount_uploader :image, ImageUploader
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :topic
  has_many :posts
  mount_uploader :image, ImageUploader
  validates :topic_id, presence: true
end

app/models/insta_account.rb
class InstaAccount < ApplicationRecord
end

app/models/insta_post.rb
class InstaPost < ApplicationRecord
end

app/models/insta_tag.rb
class InstaTag < ApplicationRecord
end

app/models/moniitor.rb
class Moniitor < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :event
  has_many :stories
  accepts_nested_attributes_for :stories

  def stories_for_form
    collection = stories.where(post_id: id)
    collection.any? ? collection : stories.build
  end

  def next
    Story.where("id > ?", id).order(id: :asc).limit(1).first
  end

  def prev
    Story.where("id < ?", id).order(id: :desc).limit(1).first
  end
  
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :post
  has_many :articles
  mount_uploader :image, ImageUploader
  # accepts_nested_attributes_for :post

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :events
  has_many :posts
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @topics = Topic.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @posts = @event.posts
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :teaser, :topic_id, :date, :time, :place, :link, :image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @topics = Topic.all
    @posts = Post.all
  end

  # GET /posts/1s
  # GET /posts/1.json
  def show
    @stories = @post.stories
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:event_id, :topic_id, stories_attributes: [:teaser, :teaser_two, :image, :post_id])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @events = @topic.events
    @posts = @topic.posts
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/insta_posts_helper.rb
module InstaPostsHelper
end

app/helpers/insta_tags_helper.rb
module InstaTagsHelper
end

app/helpers/moniitors_helper.rb
module MoniitorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="event_verh">

    <div class="zagolovok">НОВОЕ СОБЫТИЕ</div>

    <div class="event_verh_zx">
      <%= link_to events_path, :class => 'posts_back' do %>
        <div>×</div>
      <% end %>
    </div>

  </div>

  <div class="event_form_image">
    <%= form.label :image do %>
      <p>+ Изображение</p>
    <% end %>
    <%= form.file_field :image, :class => 'image_cnopca' %>
  </div>

  <!-- <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div> -->

  <div class="event_attributes">

    <div class="event_form_teaser">
      <%#= form.label :title %>
      <%= form.text_field :title, placeholder: "Добавьте заголовок...", :class => 'event_form_teaser' %>
    </div>

    <div class="event_form_teaser_two">
      <%#= form.label :teaser %>
      <%= form.text_area :teaser, placeholder: "Добавьте опиисание...", :class => 'event_form_teaser_two' %>
    </div>

    <div class="event_date">
      <%= form.label 'Волна', :class => 'event_date_date' %>
      <%#= form.number_field :topic_id %>
      <div class="event_date_date_date">
        <%= select("event", "topic_id", Topic.all.collect { |t| [ t.title, t.id ] }, { include_blank: true }) %>
      </div>
    </div>

    <div class="event_date">
      <%= form.label 'Дата', :class => 'event_date_date' %>
      <div class="event_date_date_date">
        <%= form.date_select :date, :class => 'event_date_date' %>
      </div>
    </div>

    <div class="event_date">
      <%= form.label 'Время', :class => 'event_date_date' %>
      <div class="event_date_date_date">
        <%= form.time_select :time, :class => 'event_date_date' %>
      </div>
    </div>

    <div class="event_date">
      <%= form.label 'Место', :class => 'event_date_date' %>
      <div class="event_date_date_date">
        <%= form.text_field :place, placeholder: "Добавьте описание...", :class => 'event_form_teaser_teaser' %>
      </div>
    </div>

    <div class="event_date">
      <%= form.label 'Билеты', :class => 'event_date_date' %>
      <div class="event_date_date_date">
        <%= form.text_field :link, placeholder: "Добавьте описание...", :class => 'event_form_teaser_teaser' %>
      </div>
    </div>

    <div class="event_actions">
      <%= form.submit 'Сохранить', :class => 'save_cnopca' %>
    </div>

  </div>

<% end %>

app/views/events/_index.html.erb
<body class="body_events">

  <div class="fon"><%= image_tag ("fon.png") %></div>

  <section class="waves">
    <div class="waves_scroll">
      <% @topics.each do |topic| %>
      <div class="waves_title">
        <%= topic.title %>
      </div>
      <% end %>
    </div>
  </section>

  <section class="events">

    <div class="events_zagolovok">
      <h1>ВСЕ СОБЫТИЯ</h1>
    </div>

    <div class="events_events">
      <% @events.each do |event| %>
        <div class="index_event_card">

          <%= link_to event do %>
            <div class="event_card_otkr"></div>
          <% end %>

          <div class="event_card_zatemnenie"></div>

          <div class="event_card_image <%= 'event_card_withImage' if event.image.try(:url) %><%= 'event_card_withoutImage' unless event.image.try(:url) %>">
            <div class="event_card_withoutImage">
              <%= image_tag event.image.url width: 300 if event.image.url != nil %>
            </div>
          </div>

          <div class="event_card_topic">
            <%= Topic.find(event.topic_id).title %>
          </div>
          <div class="event_card_niz">
            <div class="event_card_title">
              <%= event.title %>
            </div>
            <div class="event_card_date">
              <%= event.date %>
            </div>
            <div class="event_card_time">
              <%= event.time %>
            </div>
            <div class="event_card_place">
              <%= event.place %>
            </div>
          </div>

          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </div>
      <% end %>
    </div>

  </section>

  <%= link_to 'New Event', new_event_path %>

</body>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

<%#= link_to 'Show', @event %> 
<%#= link_to 'Back', events_path %>

app/views/events/index.html.erb
  <%= render 'layouts/application', topic: @topic %>

  <body class="body_events">

  <div class="fon"><%= image_tag ("fon.png") %></div>

  <section class="waves">
    <div class="waves_scroll">
      <% @topics.each do |topic| %>
      <div class="waves_title">
        <%= topic.title %>
      </div>
      <% end %>
    </div>
  </section>

  <section class="events">

    <div class="vse_events">

      <div class="events_zagolovok">
        <h1>ВСЕ СОБЫТИЯ</h1>
      </div>

    </div>

    <div class="events_events">
      <% @events.each do |event| %>
        <div class="index_event_card">

          <%= link_to event do %>
            <div class="event_card_otkr"></div>
          <% end %>

          <div class="event_card_zatemnenie"></div>

          <div class="event_card_image <%= 'event_card_withImage' if event.image.try(:url) %><%= 'event_card_withoutImage' unless event.image.try(:url) %>">
            <div class="event_card_withoutImage">
              <%= image_tag event.image.url width: 300 if event.image.url != nil %>
            </div>
          </div>

          <div class="event_card_topic">
            <%= Topic.find(event.topic_id).title %>
          </div>
          <div class="event_card_niz">
            <div class="event_card_title">
              <%= event.title %>
            </div>
            <div class="event_card_date">
              <%= event.date %>
            </div>
            <div class="event_card_time">
              <%= event.time %>
            </div>
            <div class="event_card_place">
              <%= event.place %>
            </div>
          </div>

          <td><%#= link_to 'Show', event %></td>
          <td><%#= link_to 'Edit', edit_event_path(event) %></td>
          <td><%#= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </div>
      <% end %>
    </div>

    <div class="plus">
      <%= link_to new_event_path, :class => 'plus_event' do %>
        <div>+ Добавить событие</div>
      <% end %>
    </div>


  </section>

</body>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%#= link_to 'Back', events_path %>

app/views/events/show.html.erb
  <%= render 'layouts/application', topic: @topic %>

  <body class="body_show_event">

  <div class="fon_show_event">
    <%= image_tag @event.image.url width: 300 if @event.image.url != nil %>
  </div>

  <section class="show_event_info">

    <div class="show_event_info_title">
      <%= @event.title %>
    </div>

    <!-- <div class="show_event_info_topic">
      <%= Topic.find(@event.topic_id).title %>
    </div> -->

    <div class="show_event_info_date">
      <%= @event.date %>
      <%= @event.time %>
    </div>

    <div class="show_event_info_place">
      <%= @event.place %>
    </div>

    <div class="show_event_info_link">Билеты
      <p><%= @event.link %></p>
    </div>

    <div class="show_event_info_teaser">Описание
      <p><%= @event.teaser %></p>
    </div>

    <div class="plus">
      <%= link_to edit_event_path(@event), :class => 'plus_event' do %>
        <div>Редактировать событие</div>
      <% end %>
    </div>

  </section>

  <!-- <%= link_to 'Back', events_path %> -->

  <!-- <section class="show_event_posts">
    <% @posts.each do |post| %>
      <%= Event.find(post.event_id).title %>
      <%= Topic.find(post.topic_id).title %>
      <%= link_to 'Show', post %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </section> -->

  <%= render 'posts/index' %>

  <div class="delete_event">
    <%= link_to @event, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'plus_event' do %>
      <div>Удалить событие</div>
    <% end %>
  </div>

</body>

app/views/posts/_form.html.erb
<body>

  <%= form_for @post do |f| %>

    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="post_verh">

      <div class="zagolovok">НОВЫЙ ПОСТ</div>

      <div class="zx">
        <%= link_to posts_path, :class => 'posts_back' do %>
          <div>×</div>
        <% end %>
      </div>

    </div>

    <div class="new_story_post">

      <div class="new_story_topic">
        <%= f.label :topic_id %>
        <%#= form.number_field :topic_id %>
        <%= select("post", "topic_id", Topic.all.collect { |t| [ t.title, t.id ] }, { include_blank: true }) %>
      </div>

      <div class="new_story_event">
        <%= f.label :event_id %>
        <%#= form.number_field :event_id %>
        <%= select("post", "event_id", Event.all.collect { |e| [ e.title, e.id ] }, { include_blank: true }) %>
      </div>

    </div>

    <div class="new_new_story">

      <!-- <div class="story_zatemnenie"></div> -->

      <div class="story_form_text">

        <%= f.fields_for :stories, @post.stories_for_form do |stories_attributes| %>

          <div class="story_form_verh_cnopki">

            <div class="story_form_image">
              <%= stories_attributes.label :image do %>
                <p>+ Изображение</p>
              <% end %>
              <%= stories_attributes.file_field :image, :class => 'image_cnopca' %>
            </div>

            <div class="actions">
              <%= f.submit 'Сохранить', :class => 'save_cnopca' %>
            </div>

          </div>

          <div class="story_form_teaser">
            <%#= f.label :teaser %>
            <%= stories_attributes.text_area :teaser, placeholder: "Добавьте заголовок...", :class => 'form_teaser' %>
          </div>

          <div class="story_form_teaser_two">
            <%#= f.label :teaser_two %>
            <%= stories_attributes.text_area :teaser_two, placeholder: "Добавьте описание...", :class => 'form_teaser_two' %>
          </div>

        <% end %>

      </div>

    </div>

    <!-- <div class="actions">
      <%= f.submit %>
    </div> -->

  <% end %>


</body>

app/views/posts/_index.html.erb
<body class="body_posts">

  <section class="posts">

    <div class="posts_zagolovok">
      <h1>ПОСТЫ</h1>
    </div>

    <!-- <div class="posts_zagolovok">
      <h1>ПОСТЫ</h1>
    </div> -->

    <div class="posts_lenta">
      <% @posts.each do |post| %>
        <div class="posts_posts">

          <%= link_to post do %>
            <div class="post_post_otkr"></div>
          <% end %>

          <div class="post_post_zatemnenie"></div>

          <div class="posts_posts_image">
            <div class="posts_posts_withoutImage">
              <%= image_tag post.stories.first.image.url if post.stories.present? && post.stories.first.image.url.present? %>
            </div>
          </div>

          <div class="posts_posts_zagolovok">
            <!-- <div class="posts_posts_topic_title">
              <%= Topic.find(post.topic_id).title %>
            </div> -->

            <div class="posts_posts_event_title">
              <%= Event.find(post.event_id).title %>
            </div>
          </div>

          <div class="posts_posts_opisanie">

            <div class="posts_posts_teaser">
              <%= post.stories.first.teaser if post.stories.present? %>
            </div>

            <div class="posts_posts_teaser_two">
              <%= post.stories.first.teaser_two if post.stories.present? %>
            </div>

          </div>

          <%#= link_to 'Show', post %>
          <%#= link_to 'Edit', edit_post_path(post) %>
          <%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>

    <%#= link_to 'New Post', new_post_path %>

  </section>

</body>

app/views/posts/_show.html.erb
<!-- <body class="show_posts">

  <p>
    <strong>Event:</strong>
    <%= Event.find(@post.event_id).title %>
  </p>

  <p>
    <strong>Topic:</strong>
    <%= Topic.find(@post.topic_id).title %>
  </p>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>

  <%= render 'stories/index' %>


</body -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<body class="body_posts_stories_show">

  <div class="posts_stories_show_verh">

    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', posts_path %>

    <div class="posts_stories_show_verh_topic">
      <%= Topic.find(@post.topic_id).title %>
    </div>

    <div class="posts_stories_show_verh_event">
      <%= Event.find(@post.event_id).title %>
    </div>

  </div>

  <div>
    <%= render 'stories/form', story: Story.new %>
  </div>

  <div class="stories_lenta">
    <% @stories.each do |story| %>
      <div class="sroty" id="story_<%= story.id %>">
        <%= render 'stories/story', story: story %>
      </div>
    <% end %>
  </div>



</body>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <%= render 'layouts/application', topic: @topic %>

  <body class="body_posts">

  <div class="fon"><%= image_tag ("fon.png") %></div>

  <section class="waves">
    <div class="waves_scroll">
      <% @topics.each do |topic| %>
      <div class="waves_title">
        <%= topic.title %>
      </div>
      <% end %>
    </div>
  </section>

  <section class="posts">

    <div class="vse_events">
      <div class="posts_zagolovok">
        <h1>ПОСТЫ</h1>
      </div>
    </div>


    <!-- <div class="posts_zagolovok">
      <h1>ПОСТЫ</h1>
    </div> -->

    <div class="posts_lenta">
      <% @posts.each do |post| %>
        <div class="posts_posts">

          <%= link_to post do %>
            <div class="post_post_otkr"></div>
          <% end %>

          <div class="post_post_zatemnenie"></div>

          <div class="posts_posts_image">
            <div class="posts_posts_withoutImage">
              <%= image_tag post.stories.first.image.url if post.stories.present? && post.stories.first.image.url.present? %>
            </div>
          </div>

          <div class="posts_posts_zagolovok">
            <!-- <div class="posts_posts_topic_title">
              <%= Topic.find(post.topic_id).title %>
            </div> -->

            <div class="posts_posts_event_title">
              <%= Event.find(post.event_id).title %>
            </div>
          </div>

          <div class="posts_posts_opisanie">

            <div class="posts_posts_teaser">
              <%= post.stories.first.teaser if post.stories.present? %>
            </div>

            <div class="posts_posts_teaser_two">
              <%= post.stories.first.teaser_two if post.stories.present? %>
            </div>

          </div>

          <%#= link_to 'Show', post %>
          <%#= link_to 'Edit', edit_post_path(post) %>
          <%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>

    <div class="plus">
      <%= link_to new_post_path, :class => 'plus_event' do %>
        <div>+ Добавить пост</div>
      <% end %>
    </div>

  </section>

</body>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%#= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<body class="body_posts_stories_show">

  <div class="posts_stories_show_verh">

    <%#= link_to 'Edit', edit_post_path(@post) %>

    <div class="posts_stories_v">

      <div class="posts_stories_show_verh_topic">
        <%= Topic.find(@post.topic_id).title %> /
        <%= Event.find(@post.event_id).title %>
      </div>

      <div class="zx">

        <%= link_to posts_path, :class => 'posts_back' do %>
          <div>×</div>
        <% end %>
      </div>


    </div>
  </div>

  <div class="stories_lenta">

    <!-- <div class="button">

      <div class="prev_button">
        <%= link_to @post.prev, class: 'prev_button', remote: true do %>
          <%= image_tag "strelka.svg" %>
        <% end %>
      </div>

      <div class="next_button">
        <%= link_to @post.next, class: 'next_button', remote: true do %>
          <%= image_tag ("strelka.svg") %>
        <% end %>
      </div>

    </div> -->

    <div class="lenta_cscroll">

      <% @stories.each do |story| %>
        <div class="sroty" id="story_<%= story.id %>">
          <%= render 'stories/story', story: story %>
        </div>
      <% end %>

      <div class="stories_new">
        <div class="stories_new_dobavit" onclick="this.style.display='none';event.preventDefault();">
          <p>Добавить историю</p>
        </div>
        <%= render 'stories/form', story: Story.new %>
      </div>

      <div class="block">
        <p>a</p>
      </div>

    </div>
  </div>

  <div class="DELETE">
    <%= link_to @post, :class => 'posts_stories_v_delete', method: :delete, data: { confirm: 'Are you sure?' } do %>
      <div>Удалить пост</div>
    <% end %>
  </div>

</body>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
  <%= render 'layouts/application', topic: @topic %>

<%#= link_to 'Edit', edit_topic_path(@topic) %>
<%#= link_to 'Back', topics_path %>

<body class="body_events">

  <div class="fon"><%= image_tag ("fon.png") %></div>

  <section class="waves">
    <div class="waves_scroll">
      <% @topics.each do |topic| %>
      <div class="waves_title">
        <%= topic.title %>
      </div>
      <% end %>
    </div>
  </section>

  <section class="events">

    <div class="vse_events">

      <div class="events_zagolovok">
        <h1><%= @topic.title %></h1>
      </div>

      <%#= link_to 'Edit', edit_topic_path(@topic) %>
      <%= link_to 'Удалить волну', @topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'wave_delete' %>


      <!-- <%= link_to new_event_path, :class => 'plus_event' do %>
        <div>+</div>
      <% end %> -->

    </div>

    <div class="events_events">
      <% @events.each do |event| %>
        <div class="index_event_card">

          <%= link_to event do %>
            <div class="event_card_otkr"></div>
          <% end %>

          <div class="event_card_zatemnenie"></div>

          <div class="event_card_image <%= 'event_card_withImage' if event.image.try(:url) %><%= 'event_card_withoutImage' unless event.image.try(:url) %>">
            <div class="event_card_withoutImage">
              <%= image_tag event.image.url width: 300 if event.image.url != nil %>
            </div>
          </div>

          <div class="event_card_topic">
            <%= Topic.find(event.topic_id).title %>
          </div>
          <div class="event_card_niz">
            <div class="event_card_title">
              <%= event.title %>
            </div>
            <div class="event_card_date">
              <%= event.date %>
            </div>
            <div class="event_card_time">
              <%= event.time %>
            </div>
            <div class="event_card_place">
              <%= event.place %>
            </div>
          </div>

          <%#= link_to 'Show', event %>
          <%#= link_to 'Edit', edit_event_path(event) %>
          <%#= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>

        </div>
      <% end %>
    </div>

  </section>

  <%#= link_to 'New Event', new_event_path %>

</body>


<%#= render 'events/index' %>
<%= render 'posts/index' %>