config/routes.rb
Rails.application.routes.draw do
  resources :insta_posts
  resources :insta_tags
  resources :insta_accounts
  resources :moniitors
  resources :articles
  resources :stories
  resources :posts
  resources :events
  resources :topics
  get 'welcome/index'
  get 'welcome/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :story
  mount_uploader :image, ImageUploader
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :topic
  has_many :posts
  mount_uploader :image, ImageUploader
  validates :topic_id, presence: true
end

app/models/insta_account.rb
class InstaAccount < ApplicationRecord
end

app/models/insta_post.rb
class InstaPost < ApplicationRecord
end

app/models/insta_tag.rb
class InstaTag < ApplicationRecord
end

app/models/moniitor.rb
class Moniitor < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :event
  has_many :stories
  accepts_nested_attributes_for :stories

  def stories_for_form
    collection = stories.where(post_id: id)
    collection.any? ? collection : stories.build
  end

  def next
    Story.where("id > ?", id).order(id: :asc).limit(1).first
  end

  def prev
    Story.where("id < ?", id).order(id: :desc).limit(1).first
  end
  
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :post
  has_many :articles
  mount_uploader :image, ImageUploader
  # accepts_nested_attributes_for :post

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :events
  has_many :posts
end

app/controllers/insta_accounts_controller.rb
class InstaAccountsController < ApplicationController
  before_action :set_insta_account, only: [:show, :edit, :update, :destroy]

  # GET /insta_accounts
  # GET /insta_accounts.json
  def index
    @insta_accounts = InstaAccount.all
  end

  # GET /insta_accounts/1
  # GET /insta_accounts/1.json
  def show
  end

  # GET /insta_accounts/new
  def new
    @insta_account = InstaAccount.new
  end

  # GET /insta_accounts/1/edit
  def edit
  end

  # POST /insta_accounts
  # POST /insta_accounts.json
  def create
    @insta_account = InstaAccount.new(insta_account_params)

    respond_to do |format|
      if @insta_account.save
        format.html { redirect_to @insta_account, notice: 'Insta account was successfully created.' }
        format.json { render :show, status: :created, location: @insta_account }
      else
        format.html { render :new }
        format.json { render json: @insta_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insta_accounts/1
  # PATCH/PUT /insta_accounts/1.json
  def update
    respond_to do |format|
      if @insta_account.update(insta_account_params)
        format.html { redirect_to @insta_account, notice: 'Insta account was successfully updated.' }
        format.json { render :show, status: :ok, location: @insta_account }
      else
        format.html { render :edit }
        format.json { render json: @insta_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insta_accounts/1
  # DELETE /insta_accounts/1.json
  def destroy
    @insta_account.destroy
    respond_to do |format|
      format.html { redirect_to insta_accounts_url, notice: 'Insta account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insta_account
      @insta_account = InstaAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insta_account_params
      params.require(:insta_account).permit(:name, :moniitor_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @topics = Topic.all
    @posts = Post.all
  end

  # GET /posts/1s
  # GET /posts/1.json
  def show
    @stories = @post.stories
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:event_id, :topic_id, stories_attributes: [:teaser, :teaser_two, :image, :post_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/insta_accounts_helper.rb
module InstaAccountsHelper
end

app/helpers/insta_posts_helper.rb
module InstaPostsHelper
end

app/helpers/insta_tags_helper.rb
module InstaTagsHelper
end

app/helpers/moniitors_helper.rb
module MoniitorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/insta_accounts/_form.html.erb
<body class="insta_body">

  <%= form_with(model: insta_account, local: true) do |form| %>
    <% if insta_account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(insta_account.errors.count, "error") %> prohibited this insta_account from being saved:</h2>

        <ul>
          <% insta_account.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :moniitor_id %>
      <%#= form.number_field :moniitor_id %>
      <%= select("insta_account", "moniitor_id", Moniitor.all.collect { |m| [ m.title, m.id ] }, { include_blank: true }) %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</body>

app/views/insta_accounts/edit.html.erb
<h1>Editing Insta Account</h1>

<%= render 'form', insta_account: @insta_account %>

<%= link_to 'Show', @insta_account %> |
<%= link_to 'Back', insta_accounts_path %>

app/views/insta_accounts/index.html.erb
<body class="insta_body">

  <h1>Insta Accounts</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Moniitor</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @insta_accounts.each do |insta_account| %>
        <tr>
          <td><%= insta_account.name %></td>
          <td><%= insta_account.moniitor_id %></td>
          <td><%= link_to 'Show', insta_account %></td>
          <td><%= link_to 'Edit', edit_insta_account_path(insta_account) %></td>
          <td><%= link_to 'Destroy', insta_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Insta Account', new_insta_account_path %>

</body>

app/views/insta_accounts/new.html.erb
<h1>New Insta Account</h1>

<%= render 'form', insta_account: @insta_account %>

<%= link_to 'Back', insta_accounts_path %>

app/views/insta_accounts/show.html.erb
<body class="insta_body">

  <p>
    <strong>Name:</strong>
    <%= @insta_account.name %>
  </p>

  <p>
    <strong>Moniitor:</strong>
    <%= Moniitor.find(@insta_account.moniitor_id).title %>
  </p>

  <%= link_to 'Edit', edit_insta_account_path(@insta_account) %> |
  <%= link_to 'Back', insta_accounts_path %>


</body>